// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package inside_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//游戏服务器注册到验证服务器
type C2SLogin struct {
	UserGuid             string   `protobuf:"bytes,1,opt,name=userGuid,proto3" json:"userGuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogin) Reset()         { *m = C2SLogin{} }
func (m *C2SLogin) String() string { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()    {}
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *C2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogin.Unmarshal(m, b)
}
func (m *C2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogin.Marshal(b, m, deterministic)
}
func (m *C2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogin.Merge(m, src)
}
func (m *C2SLogin) XXX_Size() int {
	return xxx_messageInfo_C2SLogin.Size(m)
}
func (m *C2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogin proto.InternalMessageInfo

func (m *C2SLogin) GetUserGuid() string {
	if m != nil {
		return m.UserGuid
	}
	return ""
}

//接收注册的消息
type S2CLogin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (m *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(m, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func init() {
	proto.RegisterType((*C2SLogin)(nil), "inside_proto.c2s_login")
	proto.RegisterType((*S2CLogin)(nil), "inside_proto.s2c_login")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0xcc, 0x2b, 0xce, 0x4c, 0x49, 0x8d, 0x07,
	0xf3, 0x94, 0xd4, 0xb9, 0x38, 0x93, 0x8d, 0x8a, 0xe3, 0x73, 0xf2, 0xd3, 0x33, 0xf3, 0x84, 0xa4,
	0xb8, 0x38, 0x4a, 0x8b, 0x53, 0x8b, 0xdc, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xe0, 0x7c, 0x25, 0x6e, 0x2e, 0xce, 0x62, 0xa3, 0x64, 0x88, 0xc2, 0x24, 0x36, 0xb0, 0x66,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xd1, 0x0d, 0x90, 0x58, 0x00, 0x00, 0x00,
}
