// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_grpc.proto

package inside_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//游戏服务器注册到验证服务器
type C2S_Register struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_Register) Reset()         { *m = C2S_Register{} }
func (m *C2S_Register) String() string { return proto.CompactTextString(m) }
func (*C2S_Register) ProtoMessage()    {}
func (*C2S_Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_38909006c036dd04, []int{0}
}

func (m *C2S_Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Register.Unmarshal(m, b)
}
func (m *C2S_Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Register.Marshal(b, m, deterministic)
}
func (m *C2S_Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Register.Merge(m, src)
}
func (m *C2S_Register) XXX_Size() int {
	return xxx_messageInfo_C2S_Register.Size(m)
}
func (m *C2S_Register) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Register.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Register proto.InternalMessageInfo

//接收注册的消息
type S2C_Register struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2C_Register) Reset()         { *m = S2C_Register{} }
func (m *S2C_Register) String() string { return proto.CompactTextString(m) }
func (*S2C_Register) ProtoMessage()    {}
func (*S2C_Register) Descriptor() ([]byte, []int) {
	return fileDescriptor_38909006c036dd04, []int{1}
}

func (m *S2C_Register) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_Register.Unmarshal(m, b)
}
func (m *S2C_Register) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_Register.Marshal(b, m, deterministic)
}
func (m *S2C_Register) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_Register.Merge(m, src)
}
func (m *S2C_Register) XXX_Size() int {
	return xxx_messageInfo_S2C_Register.Size(m)
}
func (m *S2C_Register) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_Register.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_Register proto.InternalMessageInfo

//玩家登陆game服务，game服务向auth服务器验证请求
type C2S_UserLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserGuid             string   `protobuf:"bytes,2,opt,name=userGuid,proto3" json:"userGuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2S_UserLogin) Reset()         { *m = C2S_UserLogin{} }
func (m *C2S_UserLogin) String() string { return proto.CompactTextString(m) }
func (*C2S_UserLogin) ProtoMessage()    {}
func (*C2S_UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_38909006c036dd04, []int{2}
}

func (m *C2S_UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_UserLogin.Unmarshal(m, b)
}
func (m *C2S_UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_UserLogin.Marshal(b, m, deterministic)
}
func (m *C2S_UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_UserLogin.Merge(m, src)
}
func (m *C2S_UserLogin) XXX_Size() int {
	return xxx_messageInfo_C2S_UserLogin.Size(m)
}
func (m *C2S_UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_UserLogin proto.InternalMessageInfo

func (m *C2S_UserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2S_UserLogin) GetUserGuid() string {
	if m != nil {
		return m.UserGuid
	}
	return ""
}

//接收注册的消息
type S2C_UserLogin struct {
	Code                 E_LoginCode `protobuf:"varint,1,opt,name=code,proto3,enum=inside_proto.E_LoginCode" json:"code,omitempty"`
	Info                 *S_UserInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2C_UserLogin) Reset()         { *m = S2C_UserLogin{} }
func (m *S2C_UserLogin) String() string { return proto.CompactTextString(m) }
func (*S2C_UserLogin) ProtoMessage()    {}
func (*S2C_UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_38909006c036dd04, []int{3}
}

func (m *S2C_UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2C_UserLogin.Unmarshal(m, b)
}
func (m *S2C_UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2C_UserLogin.Marshal(b, m, deterministic)
}
func (m *S2C_UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C_UserLogin.Merge(m, src)
}
func (m *S2C_UserLogin) XXX_Size() int {
	return xxx_messageInfo_S2C_UserLogin.Size(m)
}
func (m *S2C_UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2C_UserLogin proto.InternalMessageInfo

func (m *S2C_UserLogin) GetCode() E_LoginCode {
	if m != nil {
		return m.Code
	}
	return E_LoginCode_L_Success
}

func (m *S2C_UserLogin) GetInfo() *S_UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S_Register)(nil), "inside_proto.C2S_Register")
	proto.RegisterType((*S2C_Register)(nil), "inside_proto.S2C_Register")
	proto.RegisterType((*C2S_UserLogin)(nil), "inside_proto.C2S_UserLogin")
	proto.RegisterType((*S2C_UserLogin)(nil), "inside_proto.S2C_UserLogin")
}

func init() { proto.RegisterFile("proto_grpc.proto", fileDescriptor_38909006c036dd04) }

var fileDescriptor_38909006c036dd04 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0x54, 0xd1, 0xd1, 0x06, 0x5d, 0x44, 0xca, 0x6a, 0x41, 0x7a, 0xf2, 0x14, 0x25,
	0xfe, 0x02, 0x09, 0x22, 0x82, 0x07, 0x49, 0x28, 0x78, 0x0b, 0x75, 0x33, 0x0d, 0x8b, 0x75, 0x36,
	0xee, 0x87, 0xd0, 0x9f, 0xe7, 0x3f, 0x93, 0xec, 0xb6, 0xa9, 0xfd, 0xb8, 0xe5, 0xcd, 0xf3, 0xce,
	0xc3, 0xec, 0xc0, 0x59, 0xa3, 0x95, 0x55, 0x65, 0xad, 0x1b, 0x91, 0xf8, 0x4f, 0x16, 0x4b, 0xb2,
	0xa8, 0x69, 0x32, 0x2b, 0x7d, 0xe6, 0x2c, 0x34, 0x8c, 0xd5, 0x4e, 0xd8, 0xd0, 0xe1, 0x8b, 0x29,
	0x24, 0xf7, 0x15, 0xfe, 0x8c, 0x62, 0x38, 0xcd, 0xd2, 0xa2, 0xcc, 0xb1, 0x96, 0xc6, 0xa2, 0x6e,
	0x73, 0x91, 0x66, 0xab, 0xfc, 0x08, 0xfd, 0x96, 0x8f, 0x0d, 0xea, 0x57, 0x55, 0x4b, 0x62, 0x17,
	0x70, 0x60, 0xd5, 0x27, 0xd2, 0x20, 0xba, 0x89, 0x6e, 0x8f, 0xf3, 0x10, 0x18, 0x87, 0x23, 0x67,
	0x50, 0x3f, 0x3b, 0x59, 0x0d, 0xf6, 0x3d, 0xe8, 0xf2, 0xa8, 0x81, 0x7e, 0xab, 0x5c, 0x29, 0xee,
	0xa0, 0x27, 0x54, 0x85, 0xde, 0x10, 0xa7, 0x57, 0xc9, 0xfa, 0xe2, 0xc9, 0x53, 0xe9, 0x6b, 0x99,
	0xaa, 0x30, 0xf7, 0x45, 0x96, 0x40, 0x4f, 0xd2, 0x54, 0x79, 0xf3, 0x49, 0xca, 0x37, 0x07, 0xc2,
	0x7a, 0x2f, 0x34, 0x55, 0xb9, 0xef, 0xa5, 0xbf, 0x11, 0xc4, 0x05, 0xea, 0x1f, 0x29, 0x30, 0x53,
	0x44, 0x28, 0x2c, 0x7b, 0x87, 0xcb, 0xe5, 0x9b, 0x16, 0x24, 0xc7, 0x6f, 0x87, 0xc6, 0xb2, 0xeb,
	0x4d, 0xdd, 0xff, 0x7b, 0xf0, 0x2d, 0xba, 0x76, 0x9d, 0xbd, 0xfb, 0x88, 0x8d, 0xe1, 0xbc, 0x98,
	0x93, 0x78, 0x9b, 0x4d, 0xe6, 0xa8, 0x97, 0xd2, 0xe1, 0x2e, 0x69, 0x77, 0x01, 0x3e, 0xdc, 0x65,
	0xed, 0x70, 0xab, 0xfd, 0x38, 0xf4, 0xe0, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x17, 0x89,
	0x41, 0xe9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceConnectClient is the client API for ServiceConnect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceConnectClient interface {
	RegisterServiceRequest(ctx context.Context, in *C2S_Register, opts ...grpc.CallOption) (ServiceConnect_RegisterServiceRequestClient, error)
	SyncPlayerRequest(ctx context.Context, in *C2S_UserLogin, opts ...grpc.CallOption) (ServiceConnect_SyncPlayerRequestClient, error)
}

type serviceConnectClient struct {
	cc *grpc.ClientConn
}

func NewServiceConnectClient(cc *grpc.ClientConn) ServiceConnectClient {
	return &serviceConnectClient{cc}
}

func (c *serviceConnectClient) RegisterServiceRequest(ctx context.Context, in *C2S_Register, opts ...grpc.CallOption) (ServiceConnect_RegisterServiceRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServiceConnect_serviceDesc.Streams[0], "/inside_proto.ServiceConnect/RegisterServiceRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceConnectRegisterServiceRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceConnect_RegisterServiceRequestClient interface {
	Recv() (*S2C_Register, error)
	grpc.ClientStream
}

type serviceConnectRegisterServiceRequestClient struct {
	grpc.ClientStream
}

func (x *serviceConnectRegisterServiceRequestClient) Recv() (*S2C_Register, error) {
	m := new(S2C_Register)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceConnectClient) SyncPlayerRequest(ctx context.Context, in *C2S_UserLogin, opts ...grpc.CallOption) (ServiceConnect_SyncPlayerRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ServiceConnect_serviceDesc.Streams[1], "/inside_proto.ServiceConnect/SyncPlayerRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceConnectSyncPlayerRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceConnect_SyncPlayerRequestClient interface {
	Recv() (*S2C_UserLogin, error)
	grpc.ClientStream
}

type serviceConnectSyncPlayerRequestClient struct {
	grpc.ClientStream
}

func (x *serviceConnectSyncPlayerRequestClient) Recv() (*S2C_UserLogin, error) {
	m := new(S2C_UserLogin)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceConnectServer is the server API for ServiceConnect service.
type ServiceConnectServer interface {
	RegisterServiceRequest(*C2S_Register, ServiceConnect_RegisterServiceRequestServer) error
	SyncPlayerRequest(*C2S_UserLogin, ServiceConnect_SyncPlayerRequestServer) error
}

// UnimplementedServiceConnectServer can be embedded to have forward compatible implementations.
type UnimplementedServiceConnectServer struct {
}

func (*UnimplementedServiceConnectServer) RegisterServiceRequest(req *C2S_Register, srv ServiceConnect_RegisterServiceRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method RegisterServiceRequest not implemented")
}
func (*UnimplementedServiceConnectServer) SyncPlayerRequest(req *C2S_UserLogin, srv ServiceConnect_SyncPlayerRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncPlayerRequest not implemented")
}

func RegisterServiceConnectServer(s *grpc.Server, srv ServiceConnectServer) {
	s.RegisterService(&_ServiceConnect_serviceDesc, srv)
}

func _ServiceConnect_RegisterServiceRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(C2S_Register)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceConnectServer).RegisterServiceRequest(m, &serviceConnectRegisterServiceRequestServer{stream})
}

type ServiceConnect_RegisterServiceRequestServer interface {
	Send(*S2C_Register) error
	grpc.ServerStream
}

type serviceConnectRegisterServiceRequestServer struct {
	grpc.ServerStream
}

func (x *serviceConnectRegisterServiceRequestServer) Send(m *S2C_Register) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceConnect_SyncPlayerRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(C2S_UserLogin)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceConnectServer).SyncPlayerRequest(m, &serviceConnectSyncPlayerRequestServer{stream})
}

type ServiceConnect_SyncPlayerRequestServer interface {
	Send(*S2C_UserLogin) error
	grpc.ServerStream
}

type serviceConnectSyncPlayerRequestServer struct {
	grpc.ServerStream
}

func (x *serviceConnectSyncPlayerRequestServer) Send(m *S2C_UserLogin) error {
	return x.ServerStream.SendMsg(m)
}

var _ServiceConnect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inside_proto.ServiceConnect",
	HandlerType: (*ServiceConnectServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterServiceRequest",
			Handler:       _ServiceConnect_RegisterServiceRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncPlayerRequest",
			Handler:       _ServiceConnect_SyncPlayerRequest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto_grpc.proto",
}
