// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/internal_proto/proto_auth_game.proto

package internal_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//游戏服务器注册到网管服务
type GameConnectServiceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameConnectServiceRequest) Reset()         { *m = GameConnectServiceRequest{} }
func (m *GameConnectServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GameConnectServiceRequest) ProtoMessage()    {}
func (*GameConnectServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3bc802027c54b3a, []int{0}
}

func (m *GameConnectServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameConnectServiceRequest.Unmarshal(m, b)
}
func (m *GameConnectServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameConnectServiceRequest.Marshal(b, m, deterministic)
}
func (m *GameConnectServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameConnectServiceRequest.Merge(m, src)
}
func (m *GameConnectServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GameConnectServiceRequest.Size(m)
}
func (m *GameConnectServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameConnectServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameConnectServiceRequest proto.InternalMessageInfo

//接收注册的消息
type GameConnectServiceReply struct {
	IsConnected          bool     `protobuf:"varint,1,opt,name=isConnected,proto3" json:"isConnected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameConnectServiceReply) Reset()         { *m = GameConnectServiceReply{} }
func (m *GameConnectServiceReply) String() string { return proto.CompactTextString(m) }
func (*GameConnectServiceReply) ProtoMessage()    {}
func (*GameConnectServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3bc802027c54b3a, []int{1}
}

func (m *GameConnectServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameConnectServiceReply.Unmarshal(m, b)
}
func (m *GameConnectServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameConnectServiceReply.Marshal(b, m, deterministic)
}
func (m *GameConnectServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameConnectServiceReply.Merge(m, src)
}
func (m *GameConnectServiceReply) XXX_Size() int {
	return xxx_messageInfo_GameConnectServiceReply.Size(m)
}
func (m *GameConnectServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GameConnectServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GameConnectServiceReply proto.InternalMessageInfo

func (m *GameConnectServiceReply) GetIsConnected() bool {
	if m != nil {
		return m.IsConnected
	}
	return false
}

//请求玩家是否登陆
type GamePlayerLoginRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePlayerLoginRequest) Reset()         { *m = GamePlayerLoginRequest{} }
func (m *GamePlayerLoginRequest) String() string { return proto.CompactTextString(m) }
func (*GamePlayerLoginRequest) ProtoMessage()    {}
func (*GamePlayerLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3bc802027c54b3a, []int{2}
}

func (m *GamePlayerLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePlayerLoginRequest.Unmarshal(m, b)
}
func (m *GamePlayerLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePlayerLoginRequest.Marshal(b, m, deterministic)
}
func (m *GamePlayerLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePlayerLoginRequest.Merge(m, src)
}
func (m *GamePlayerLoginRequest) XXX_Size() int {
	return xxx_messageInfo_GamePlayerLoginRequest.Size(m)
}
func (m *GamePlayerLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePlayerLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GamePlayerLoginRequest proto.InternalMessageInfo

func (m *GamePlayerLoginRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

//验证玩家是否登陆
type GamePlayerLoginReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GamePlayerLoginReply) Reset()         { *m = GamePlayerLoginReply{} }
func (m *GamePlayerLoginReply) String() string { return proto.CompactTextString(m) }
func (*GamePlayerLoginReply) ProtoMessage()    {}
func (*GamePlayerLoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3bc802027c54b3a, []int{3}
}

func (m *GamePlayerLoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GamePlayerLoginReply.Unmarshal(m, b)
}
func (m *GamePlayerLoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GamePlayerLoginReply.Marshal(b, m, deterministic)
}
func (m *GamePlayerLoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GamePlayerLoginReply.Merge(m, src)
}
func (m *GamePlayerLoginReply) XXX_Size() int {
	return xxx_messageInfo_GamePlayerLoginReply.Size(m)
}
func (m *GamePlayerLoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GamePlayerLoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_GamePlayerLoginReply proto.InternalMessageInfo

func (m *GamePlayerLoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GameConnectServiceRequest)(nil), "internal_proto.GameConnectServiceRequest")
	proto.RegisterType((*GameConnectServiceReply)(nil), "internal_proto.GameConnectServiceReply")
	proto.RegisterType((*GamePlayerLoginRequest)(nil), "internal_proto.GamePlayerLoginRequest")
	proto.RegisterType((*GamePlayerLoginReply)(nil), "internal_proto.GamePlayerLoginReply")
}

func init() {
	proto.RegisterFile("protobuf/internal_proto/proto_auth_game.proto", fileDescriptor_b3bc802027c54b3a)
}

var fileDescriptor_b3bc802027c54b3a = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x75, 0x41, 0x45, 0xa7, 0xd0, 0xc3, 0x50, 0xaa, 0xd6, 0x4b, 0x09, 0xe2, 0x07, 0xd4, 0x2d,
	0xd4, 0xa3, 0x47, 0x0f, 0x5e, 0x3c, 0xc8, 0x0a, 0x5e, 0x97, 0xb4, 0x9d, 0xc6, 0x60, 0x9a, 0xac,
	0xf9, 0x10, 0x72, 0xf3, 0xa7, 0x4b, 0xd3, 0x08, 0x5d, 0x5a, 0xd1, 0x4b, 0xc8, 0x9b, 0xf7, 0x66,
	0xde, 0xbc, 0x81, 0xdb, 0xc6, 0x1a, 0x6f, 0xa6, 0x61, 0x31, 0x96, 0xda, 0x93, 0xd5, 0x5c, 0xd5,
	0xa9, 0x32, 0x4e, 0x6f, 0xcd, 0x83, 0x7f, 0xab, 0x05, 0x5f, 0x52, 0x99, 0x30, 0x76, 0xdb, 0x2a,
	0x76, 0x0e, 0x67, 0x8f, 0x7c, 0x49, 0x0f, 0x46, 0x6b, 0x9a, 0xf9, 0x17, 0xb2, 0x9f, 0x72, 0x46,
	0x15, 0x7d, 0x04, 0x72, 0x9e, 0xdd, 0xc3, 0xc9, 0x2e, 0xb2, 0x51, 0x11, 0x87, 0xd0, 0x91, 0x2e,
	0x13, 0x34, 0x3f, 0x2d, 0x86, 0xc5, 0xf5, 0x51, 0xb5, 0x59, 0x62, 0x23, 0xe8, 0xaf, 0x9a, 0x9f,
	0x15, 0x8f, 0x64, 0x9f, 0x8c, 0x90, 0x3a, 0x8f, 0x45, 0x84, 0x7d, 0x11, 0xe4, 0xba, 0xe9, 0xb8,
	0x4a, 0x7f, 0x36, 0x82, 0xde, 0x96, 0x7a, 0xe5, 0xd3, 0x83, 0x03, 0x6f, 0xde, 0x49, 0x67, 0xf1,
	0x1a, 0x4c, 0xbe, 0x0a, 0xe8, 0xe6, 0x75, 0xb2, 0x21, 0x6a, 0xe8, 0x57, 0x24, 0xa4, 0xf3, 0x64,
	0xdb, 0x29, 0xf0, 0xa6, 0x6c, 0x67, 0x2e, 0x7f, 0x0d, 0x3c, 0xb8, 0xfa, 0x8f, 0xb4, 0x51, 0x91,
	0xed, 0x4d, 0x1c, 0x74, 0xd2, 0x9a, 0xaf, 0x64, 0xe5, 0x22, 0xe2, 0x1c, 0x70, 0x03, 0xfe, 0x58,
	0x5f, 0xee, 0x9a, 0xb7, 0x7d, 0x91, 0xc1, 0xc5, 0x9f, 0xba, 0x64, 0x3a, 0x3d, 0x4c, 0xec, 0xdd,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x09, 0xe0, 0xa7, 0xf5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceConnectClient is the client API for ServiceConnect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceConnectClient interface {
	RegisterServiceRequest(ctx context.Context, in *GameConnectServiceRequest, opts ...grpc.CallOption) (*GameConnectServiceReply, error)
}

type serviceConnectClient struct {
	cc *grpc.ClientConn
}

func NewServiceConnectClient(cc *grpc.ClientConn) ServiceConnectClient {
	return &serviceConnectClient{cc}
}

func (c *serviceConnectClient) RegisterServiceRequest(ctx context.Context, in *GameConnectServiceRequest, opts ...grpc.CallOption) (*GameConnectServiceReply, error) {
	out := new(GameConnectServiceReply)
	err := c.cc.Invoke(ctx, "/internal_proto.ServiceConnect/RegisterServiceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceConnectServer is the server API for ServiceConnect service.
type ServiceConnectServer interface {
	RegisterServiceRequest(context.Context, *GameConnectServiceRequest) (*GameConnectServiceReply, error)
}

// UnimplementedServiceConnectServer can be embedded to have forward compatible implementations.
type UnimplementedServiceConnectServer struct {
}

func (*UnimplementedServiceConnectServer) RegisterServiceRequest(ctx context.Context, req *GameConnectServiceRequest) (*GameConnectServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServiceRequest not implemented")
}

func RegisterServiceConnectServer(s *grpc.Server, srv ServiceConnectServer) {
	s.RegisterService(&_ServiceConnect_serviceDesc, srv)
}

func _ServiceConnect_RegisterServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameConnectServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceConnectServer).RegisterServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal_proto.ServiceConnect/RegisterServiceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceConnectServer).RegisterServiceRequest(ctx, req.(*GameConnectServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceConnect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal_proto.ServiceConnect",
	HandlerType: (*ServiceConnectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterServiceRequest",
			Handler:    _ServiceConnect_RegisterServiceRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/internal_proto/proto_auth_game.proto",
}

// LoginVerifyClient is the client API for LoginVerify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginVerifyClient interface {
	LoginVerifyRequest(ctx context.Context, in *GamePlayerLoginRequest, opts ...grpc.CallOption) (*GamePlayerLoginReply, error)
}

type loginVerifyClient struct {
	cc *grpc.ClientConn
}

func NewLoginVerifyClient(cc *grpc.ClientConn) LoginVerifyClient {
	return &loginVerifyClient{cc}
}

func (c *loginVerifyClient) LoginVerifyRequest(ctx context.Context, in *GamePlayerLoginRequest, opts ...grpc.CallOption) (*GamePlayerLoginReply, error) {
	out := new(GamePlayerLoginReply)
	err := c.cc.Invoke(ctx, "/internal_proto.LoginVerify/LoginVerifyRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginVerifyServer is the server API for LoginVerify service.
type LoginVerifyServer interface {
	LoginVerifyRequest(context.Context, *GamePlayerLoginRequest) (*GamePlayerLoginReply, error)
}

// UnimplementedLoginVerifyServer can be embedded to have forward compatible implementations.
type UnimplementedLoginVerifyServer struct {
}

func (*UnimplementedLoginVerifyServer) LoginVerifyRequest(ctx context.Context, req *GamePlayerLoginRequest) (*GamePlayerLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginVerifyRequest not implemented")
}

func RegisterLoginVerifyServer(s *grpc.Server, srv LoginVerifyServer) {
	s.RegisterService(&_LoginVerify_serviceDesc, srv)
}

func _LoginVerify_LoginVerifyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GamePlayerLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginVerifyServer).LoginVerifyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal_proto.LoginVerify/LoginVerifyRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginVerifyServer).LoginVerifyRequest(ctx, req.(*GamePlayerLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoginVerify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal_proto.LoginVerify",
	HandlerType: (*LoginVerifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginVerifyRequest",
			Handler:    _LoginVerify_LoginVerifyRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/internal_proto/proto_auth_game.proto",
}
