// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_struct.proto

package internal_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//游戏服务器注册到网管服务
type Request_ConnectStruct struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_ConnectStruct) Reset()         { *m = Request_ConnectStruct{} }
func (m *Request_ConnectStruct) String() string { return proto.CompactTextString(m) }
func (*Request_ConnectStruct) ProtoMessage()    {}
func (*Request_ConnectStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc4bef41498765a3, []int{0}
}

func (m *Request_ConnectStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_ConnectStruct.Unmarshal(m, b)
}
func (m *Request_ConnectStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_ConnectStruct.Marshal(b, m, deterministic)
}
func (m *Request_ConnectStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_ConnectStruct.Merge(m, src)
}
func (m *Request_ConnectStruct) XXX_Size() int {
	return xxx_messageInfo_Request_ConnectStruct.Size(m)
}
func (m *Request_ConnectStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_ConnectStruct.DiscardUnknown(m)
}

var xxx_messageInfo_Request_ConnectStruct proto.InternalMessageInfo

//接收注册的消息
type Response_ConnectStruct struct {
	IsConnected          bool     `protobuf:"varint,1,opt,name=isConnected,proto3" json:"isConnected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_ConnectStruct) Reset()         { *m = Response_ConnectStruct{} }
func (m *Response_ConnectStruct) String() string { return proto.CompactTextString(m) }
func (*Response_ConnectStruct) ProtoMessage()    {}
func (*Response_ConnectStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc4bef41498765a3, []int{1}
}

func (m *Response_ConnectStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_ConnectStruct.Unmarshal(m, b)
}
func (m *Response_ConnectStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_ConnectStruct.Marshal(b, m, deterministic)
}
func (m *Response_ConnectStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ConnectStruct.Merge(m, src)
}
func (m *Response_ConnectStruct) XXX_Size() int {
	return xxx_messageInfo_Response_ConnectStruct.Size(m)
}
func (m *Response_ConnectStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ConnectStruct.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ConnectStruct proto.InternalMessageInfo

func (m *Response_ConnectStruct) GetIsConnected() bool {
	if m != nil {
		return m.IsConnected
	}
	return false
}

func init() {
	proto.RegisterType((*Request_ConnectStruct)(nil), "internal_proto.Request_ConnectStruct")
	proto.RegisterType((*Response_ConnectStruct)(nil), "internal_proto.Response_ConnectStruct")
}

func init() { proto.RegisterFile("proto_struct.proto", fileDescriptor_fc4bef41498765a3) }

var fileDescriptor_fc4bef41498765a3 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x2f, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0xd1, 0x03, 0x73, 0x84, 0xf8, 0x32, 0xf3, 0x4a,
	0x52, 0x8b, 0xf2, 0x12, 0x73, 0xe2, 0xc1, 0x7c, 0x25, 0x71, 0x2e, 0xd1, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x92, 0x78, 0xe7, 0xfc, 0xbc, 0xbc, 0xd4, 0xe4, 0x92, 0x60, 0xb0, 0x72, 0x25, 0x2b,
	0x2e, 0xb1, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x54, 0x19, 0x21, 0x05, 0x2e, 0xee,
	0xcc, 0x62, 0xa8, 0x50, 0x6a, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x47, 0x10, 0xb2, 0x50, 0x12,
	0x1b, 0xd8, 0x6c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xac, 0x65, 0xf3, 0x81, 0x00,
	0x00, 0x00,
}
