// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package internal_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2S_Body struct {
	Register             *C2S_Register `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *C2S_Body) Reset()         { *m = C2S_Body{} }
func (m *C2S_Body) String() string { return proto.CompactTextString(m) }
func (*C2S_Body) ProtoMessage()    {}
func (*C2S_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *C2S_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2S_Body.Unmarshal(m, b)
}
func (m *C2S_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2S_Body.Marshal(b, m, deterministic)
}
func (m *C2S_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S_Body.Merge(m, src)
}
func (m *C2S_Body) XXX_Size() int {
	return xxx_messageInfo_C2S_Body.Size(m)
}
func (m *C2S_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S_Body.DiscardUnknown(m)
}

var xxx_messageInfo_C2S_Body proto.InternalMessageInfo

func (m *C2S_Body) GetRegister() *C2S_Register {
	if m != nil {
		return m.Register
	}
	return nil
}

func init() {
	proto.RegisterType((*C2S_Body)(nil), "internal_proto.C2S_Body")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0xcc, 0x2b, 0x49, 0x2d,
	0xca, 0x4b, 0xcc, 0x89, 0x07, 0xf3, 0xa5, 0x84, 0xc0, 0x54, 0x7c, 0x71, 0x49, 0x51, 0x69, 0x32,
	0x54, 0x8d, 0x92, 0x0b, 0x17, 0x87, 0xb3, 0x51, 0x70, 0xbc, 0x53, 0x7e, 0x4a, 0xa5, 0x90, 0x05,
	0x17, 0x47, 0x51, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x6a, 0x91, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7,
	0x91, 0x8c, 0x1e, 0xaa, 0x11, 0x7a, 0x20, 0xb5, 0x41, 0x50, 0x35, 0x41, 0x70, 0xd5, 0x49, 0x6c,
	0x60, 0x59, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe1, 0xd7, 0x76, 0x81, 0x00, 0x00,
	0x00,
}
